ProjectRoot = "D:\\HJKIM\\RT-RAM-grpc"
EGO_ID = 1

DURATION = 0.1

# seconds
HISTORY_WINDOW_TIME = 3
FUTURE_PREDICT_TIME = 5
# NUM
HISTORY_SIZE = HISTORY_WINDOW_TIME / DURATION
FUTURE_SIZE = FUTURE_PREDICT_TIME / DURATION
DOWNSAMPLING_RATE = 2
# meter
LANE_WIDTH = 3.5
GRID_LONGITUDE = 27
GRID_SIZE = (13, 3)
EGO_POS = (GRID_SIZE[0] // 2, GRID_SIZE[1] // 2)
EGO_IDX = (GRID_SIZE[0]*GRID_SIZE[1]) // 2
SCENE_SIZE = (GRID_LONGITUDE*2, LANE_WIDTH*3)

# calculate risk
WIDTH = 1.2
LENGTH = 2.4
SAFE_DIS = 1
